name: Create Terraform Workspace
on:
  workflow_dispatch:
    inputs:
      workspace_name:
        description: 'Workspace Name'
        required: true
        type: string
      working_directory:
        description: 'Working Directory'
        required: true
        default: 'awsenv/dev/env'
        type: choice
        options:
          - awsenv/dev/env
          - awsenv/dev/group

jobs:
  create-workspace:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Create directory
        run: mkdir -p awsenv/dev/env
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.5

      - name: Terraform Init
        run: terraform init -upgrade
        working-directory: awsenv/dev/env
      
      - name: check if workspace exists
        id: check_workspace
        run: 
          if terraform workspace list | grep -q "${{ github.event.inputs.workspace_name }}"; then
            echo "Workspace already exists"
            exit 1
          else
            echo "Workspace does not exist"
          fi
        working-directory: awsenv/dev/env

      - name: Create new workspace
        if: steps.check_workspace.outcome == 'success'
        run: terraform workspace new "${{ github.event.inputs.workspace_name }}"
        working-directory: awsenv/dev/env