name: Terraform Plan and Apply
on:
  workflow_dispatch:
jobs:
  create-workspace:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.5

      - name: Terraform Init
        run: terraform init
        working-directory: awsenv/dev/env

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan
        working-directory: awsenv/dev/env

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: awsenv/dev/env
      